{
 "title": "Crisipo",
 "time": { "from": "2020-05-01T16:58:53.834Z", "to": "2020-05-01T19:03:44.065Z" },
 "panels": [
  {
   "title": "Load/Temp",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max_over_time(crisipo_node_load1[5m])",
     "legendFormat": "1 min"
    },
    {
     "expr": "max_over_time(crisipo_node_thermal_zone_temp[5m])",
     "legendFormat": "cpu_temp"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 0 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "(max_over_time(crisipo_node_memory_MemFree_bytes[5m])) / (1024*1024)",
     "legendFormat": "Free"
    },
    {
     "expr": "(max_over_time(crisipo_node_memory_MemTotal_bytes[5m]) - max_over_time(crisipo_node_memory_MemAvailable_bytes[5m])) / (1024*1024)",
     "legendFormat": "In Use"
    },
    {
     "expr": "(max_over_time(crisipo_node_memory_MemAvailable_bytes[5m]) - max_over_time(crisipo_node_memory_MemFree_bytes[5m]) ) / (1024*1024)",
     "legendFormat": "Cached"
    }
   ]
  },
  {
   "title": "DIsk IO",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "expr": "idelta(crisipo_node_disk_read_bytes_total[15m]) / 900 /1024",
     "legendFormat": "Read {{device}}"
    },
    {
     "expr": "idelta(crisipo_node_disk_written_bytes_total[15m]) / 900 /1024",
     "legendFormat": "Write {{device}}"
    }
   ]
  },
  {
   "title": "CPU Freq",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "expr": "max_over_time(crisipo_node_cpu_frequency_hertz[10m])",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 8 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "crisipo_node_time_seconds - crisipo_node_boot_time_seconds"
    }
   ]
  },
  {
   "title": "Filesystems",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * (max_over_time(crisipo_node_filesystem_size_bytes[5m]) - max_over_time(crisipo_node_filesystem_free_bytes[5m])) / max_over_time(crisipo_node_filesystem_size_bytes[5m])",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "8*idelta(crisipo_node_network_receive_bytes_total[15m])/900",
     "legendFormat": "RX {{device}}"
    },
    {
     "expr": "8*idelta(crisipo_node_network_transmit_bytes_total[15m])/900",
     "legendFormat": "TX {{device}}"
    }
   ]
  }
 ]
}