{
 "title": "Hecuba",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Load/Temp",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_load1", "legendFormat": "1 min" },
    { "expr": "avg_over_time(node_load1[30m])", "legendFormat": "Mean" },
    { "expr": "temp_cpu_celsius / 1000", "legendFormat": "cpu_temp" },
    { "expr": "temp_ram_celsius / 1000", "legendFormat": "ram_temp" }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 0 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "(node_memory_MemFree_bytes) / (1024*1024)",
     "legendFormat": "Free"
    },
    {
     "expr": "(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / (1024*1024)",
     "legendFormat": "In Use"
    },
    {
     "expr": "(node_memory_MemAvailable_bytes - node_memory_MemFree_bytes ) / (1024*1024)",
     "legendFormat": "Cached"
    }
   ]
  },
  {
   "title": "DIsk IO",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "expr": "idelta(node_disk_written_bytes_total{device=\"mmcblk1p1\"}[1m])/1024",
     "legendFormat": "SD Read"
    },
    {
     "expr": "idelta(node_disk_read_bytes_total{device=\"mmcblk1p1\"}[1m])/1024",
     "legendFormat": "SD Write"
    },
    {
     "expr": "idelta(node_disk_written_bytes_total{device=\"sda\"}[1m])/1024",
     "legendFormat": "BCK Write"
    },
    {
     "expr": "idelta(node_disk_read_bytes_total{device=\"sda\"}[1m])/1024",
     "legendFormat": "BCK Read"
    },
    {
     "expr": "idelta(node_disk_read_bytes_total{device=\"sdb\"}[1m])/1024",
     "legendFormat": "MAIN Read"
    },
    {
     "expr": "idelta(node_disk_written_bytes_total{device=\"sdb\"}[1m])/1024",
     "legendFormat": "MAIN Write"
    }
   ]
  },
  {
   "title": "CPU Freq",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    { "expr": "node_cpu_frequency_hertz", "legendFormat": "{{cpu}}" }
   ]
  },
  {
   "title": "Enlaces",
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 8 },
   "content": "- [**PIHOLE**](http://192.168.0.7:80/admin)\n- [**JEKYLL**](http://192.168.0.7:4000)\n- [**TRANSMISSION**](http://192.168.0.7:9091)\n\n\n"
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 11 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_time_seconds - node_boot_time_seconds"
    }
   ]
  },
  {
   "title": "Filesystems",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * (node_filesystem_size_bytes - node_filesystem_free_bytes) / node_filesystem_size_bytes",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "8*idelta(node_network_receive_bytes_total{device=\"eth0\"}[1m])/30",
     "legendFormat": "RX"
    },
    {
     "expr": "8*idelta(node_network_transmit_bytes_total{device=\"eth0\"}[1m])/30",
     "legendFormat": "TX"
    }
   ]
  },
  { "title": "Containers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "engine_daemon_container_states_containers",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Actions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(idelta(engine_daemon_container_actions_seconds_bucket{le=\"1\"}[5m])) by (action)",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(idelta(docker_container_cpu_total[10m]) / idelta(docker_container_cpu_system[10m]) *100) * docker_container_cpu_count",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Image Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "docker_img_size_bytes", "legendFormat": "{{id}}" }
   ]
  },
  {
   "title": "IO Read",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "idelta(docker_container_io_read_bytes[10m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "IO Read",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "idelta(docker_container_io_read_bytes[10m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Net Received",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "idelta(docker_container_net_rx_bytes[10m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Net Transmitted",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "idelta(docker_container_net_tx_bytes[10m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Usage (MB)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "docker_container_mem_usage_bytes",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "docker_container_mem_usage_pcnt",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}