{
 "title": "Internet (Madrid)",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  { "title": "Router", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "Kbits" }
   ],
   "targets": [
    {
     "expr": "8*idelta(crisipo_tplink_wan_rx_kbytes[15m])/ 900 >=0",
     "legendFormat": "RX"
    },
    {
     "expr": "- (8*idelta(crisipo_tplink_wan_tx_kbytes[15m])/900 >=0)",
     "legendFormat": "TX"
    }
   ]
  },
  {
   "title": "DHCP Leases",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(crisipo_tplink_lan_lease_seconds[5m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "LAN Traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "Kbits" }
   ],
   "targets": [
    {
     "expr": "8*idelta(crisipo_tplink_lan_traffic_kbytes[15m])/ 900 >=0 <=150000",
     "legendFormat": "{{ip}} ({{name}})"
    }
   ]
  },
  { "title": "DNS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "DNS Response Type",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "deriv(crisipo_pihole_reply_cname[15m]) * 900 >=0",
     "legendFormat": "CNAME"
    },
    {
     "expr": "deriv(crisipo_pihole_reply_nxdomain[15m]) * 900 >=0",
     "legendFormat": "NXDOMAIN"
    },
    {
     "expr": " deriv(pihole_reply_ip[15m]) * 900 >=0",
     "legendFormat": "IPADDR"
    },
    {
     "expr": " deriv(pihole_reply_nodata[15m]) * 900 >=0",
     "legendFormat": "NODATA"
    },
    {
     "expr": "deriv(pihole_ads_blocked_today[15m]) * 900 >=0",
     "legendFormat": "BLOCKED"
    }
   ]
  },
  {
   "title": "DNS Sources",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "deriv(crisipo_pihole_queries_cached[15m]) * 900 >=0",
     "legendFormat": "Cache"
    },
    {
     "expr": "deriv(crisipo_pihole_queries_forwarded[15m]) * 900 >=0",
     "legendFormat": "Authoritative"
    }
   ]
  }
 ]
}