{
 "title": "Weather",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Light",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "weather_light", "legendFormat": "Light" }
   ]
  },
  {
   "title": "Temp/Hum",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    { "expr": "weather_temperature", "legendFormat": "Temperature" },
    { "expr": "weather_humidity", "legendFormat": "Humidity" }
   ]
  },
  {
   "title": "Pressure",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "pressurehpa" }
   ],
   "targets": [
    { "expr": "weather_pressure + 80", "legendFormat": "Pressure" }
   ]
  }
 ]
}