    global:
      scrape_interval:     60s
      evaluation_interval: 300s

    rule_files:
      # - "first.rules"
      # - "second.rules"

    scrape_configs:

      - job_name: cloudflare_exporter
        scrape_interval: 10m
        scrape_timeout: 15s
        static_configs:
          - targets: ['cf_exporter:2112']
          
      - job_name: promrelay
        scrape_interval: 10s
        scrape_timeout: 5s
        static_configs:
          - targets: ['promrelay:9797']

      - job_name: cloudflared
        scrape_interval: 1m
        scrape_timeout: 5s
        static_configs:
          - targets: ['cloudflared:4933']

      - job_name: docker_exporter
        scrape_interval: 5m
        scrape_timeout: 60s
        static_configs:
          - targets: ['docker_exporter:9134']

      - job_name: ping_google
        scrape_interval: 10m
        scrape_timeout: 5s
        params:
          addr: ['8.8.8.8']
          count: ['3']
        static_configs:
          - targets: ['ping_exporter:9400']

      - job_name: ping_gateway
        scrape_interval: 5m
        scrape_timeout: 5s
        params:
          addr: ['192.168.0.1']
          count: ['3']
        static_configs:
          - targets: ['ping_exporter:9400']

      - job_name: ping_cloudflare
        scrape_interval: 10m
        scrape_timeout: 5s
        params:
          addr: ['1.0.0.1']
          count: ['3']
        static_configs:
          - targets: ['ping_exporter:9400']

      - job_name: 'docker'
        scrape_interval: 30s
        static_configs:
          - targets: ['192.168.0.10:9323']

      - job_name: 'node_exporter'
        scrape_interval: 30s
        static_configs:
          - targets: ['192.168.0.10:9100']

      - job_name: 'virgin'
        scrape_interval: 300s
        scrape_timeout: 60s
        static_configs:
          - targets: ['virgin_exporter:9300']

      - job_name: 'pihole'
        scrape_interval: 60s
        static_configs:
          - targets: ['pihole_exporter:9333']
          
      - job_name: 'teledoor'
        scrape_interval: 60s
        static_configs:
          - targets: ['teledoor:4865']

      - job_name: 'weather'
        scrape_interval: 30s
        static_configs:
         - targets: ['weather_exporter:9200']
