c.NotebookApp.allow_origin = '*'
c.NotebookApp.allow_remote_access = True
c.NotebookApp.base_url = '/'
c.NotebookApp.open_browser = False
c.NotebookApp.terminals_enabled = True
# c.NotebookApp.enable_mathjax = True
# c.NotebookApp.ip = '*'
# c.NotebookApp.notebook_dir = '/jupyter/Notebooks'
# c.NotebookApp.password = "sha1:113453eb1820490"
# c.NotebookApp.password_required = False
# c.NotebookApp.port = 8888
